import type { LucideIcon } from "lucide-react-native";
import {
  Backpack,
  Bath,
  Bed,
  Bell,
  Bike,
  Binoculars,
  Bird,
  BookOpen,
  Brush,
  Bug,
  Building2,
  Bus,
  CableCar,
  Calendar,
  Candy,
  Car,
  Castle,
  Cherry,
  CloudSun,
  Coffee,
  Cog,
  Compass,
  Cookie,
  CookingPot,
  Crown,
  DoorOpen,
  Drama,
  Droplets,
  Feather,
  FerrisWheel,
  Fish,
  Flag,
  Flame,
  FlaskConical,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  GitMerge,
  Globe,
  Hammer,
  HandHeart,
  HeartHandshake,
  House,
  Kayak,
  Landmark,
  Languages,
  Layers,
  Leaf,
  Library,
  Lightbulb,
  Link2,
  Luggage,
  Map,
  Megaphone,
  Mountain,
  Music,
  PartyPopper,
  PawPrint,
  Palette,
  Pickaxe,
  Plane,
  Recycle,
  Rocket,
  Route,
  Ruler,
  Scissors,
  ScrollText,
  Shield,
  Shirt,
  ShoppingBasket,
  Shovel,
  Signpost,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Store,
  Swords,
  Telescope,
  Tent,
  Thermometer,
  TrainFront,
  Trees,
  TreePine,
  TrendingUp,
  Trophy,
  Users,
  Waves,
  Wheat,
  Wind,
  Wrench,
} from "lucide-react-native";

/** Exact 1:1 mapping for the 21 top-level category icons (taxonomy.json `categories[].icon`). */
export const TAXONOMY_CATEGORY_ICONS: Record<string, LucideIcon> = {
  "mdi:image-filter-hdr": Mountain,
  "mdi:waves": Waves,
  "mdi:paw": PawPrint,
  "mdi:temple-hindu": Landmark,
  "mdi:shoe-print": Footprints,
  "mdi:party-popper": PartyPopper,
  "mdi:drama-masks": Drama,
  "mdi:silverware-fork-knife": Cookie,
  "mdi:palette-outline": Palette,
  "mdi:tools": Wrench,
  "mdi:barn": Wheat,
  "mdi:home-city": House,
  "mdi:hiking": Backpack,
  "mdi:bag-suitcase": Luggage,
  "mdi:bus": Bus,
  "mdi:bank": Library,
  "mdi:meditation": Sparkles,
  "mdi:leaf": Leaf,
  "mdi:earth": Globe,
  "mdi:account-heart": HeartHandshake,
  "mdi:trophy": Trophy,
};

/** Ordered keyword → icon table for the 164 subcategory icons — mdi/Iconify isn't available
 * per project icon rules (lucide only), so this resolves each mdi name to the closest lucide
 * equivalent by keyword. First matching keyword wins; unmatched names fall back to the
 * category's own icon (see resolveTaxonomyIcon). */
const KEYWORD_ICONS: [string, LucideIcon][] = [
  ["account", Users],
  ["airplane", Plane],
  ["alert", Shield],
  ["arm-flex", Users],
  ["basket", ShoppingBasket],
  ["beehive", Sprout],
  ["bed", Bed],
  ["bell", Bell],
  ["bicycle", Bike],
  ["binoculars", Binoculars],
  ["bird", Bird],
  ["book", BookOpen],
  ["bottle", FlaskConical],
  ["bowl", CookingPot],
  ["box-cutter", Scissors],
  ["bread", Wheat],
  ["bridge", Route],
  ["broom", Brush],
  ["brush", Brush],
  ["bullhorn", Megaphone],
  ["bus", Bus],
  ["butterfly", Bug],
  ["calendar", Calendar],
  ["call-merge", GitMerge],
  ["candle", Flame],
  ["candy", Candy],
  ["car-estate", Car],
  ["carabiner", Link2],
  ["castle", Castle],
  ["chess", Castle],
  ["city", Building2],
  ["cog", Cog],
  ["compass", Compass],
  ["corn", Wheat],
  ["cow", PawPrint],
  ["crown", Crown],
  ["cupcake", Cookie],
  ["cup", Coffee],
  ["diamond", Gem],
  ["door", DoorOpen],
  ["elevation", TrendingUp],
  ["feather", Feather],
  ["ferris-wheel", FerrisWheel],
  ["fish", Fish],
  ["flag", Flag],
  ["flower", Flower2],
  ["food-croissant", Cookie],
  ["forest", Trees],
  ["fruit", Cherry],
  ["gamepad", Gamepad2],
  ["gate", DoorOpen],
  ["gondola", CableCar],
  ["grain", Wheat],
  ["grass", Sprout],
  ["hammer", Hammer],
  ["hand-back-right", HandHeart],
  ["hand-heart", HandHeart],
  ["hands-pray", HandHeart],
  ["hanger", Shirt],
  ["helicopter", Plane],
  ["home", House],
  ["horse", PawPrint],
  ["hot-tub", Bath],
  ["human-female-dance", Music],
  ["hydro-power", Droplets],
  ["kayaking", Kayak],
  ["layers", Layers],
  ["leaf", Leaf],
  ["lightbulb", Lightbulb],
  ["map", Map],
  ["mortar-pestle", CookingPot],
  ["mushroom", Sprout],
  ["music", Music],
  ["needle", Scissors],
  ["office-building", Building2],
  ["om", Sparkles],
  ["palette", Palette],
  ["parachute", Wind],
  ["paw", PawPrint],
  ["pickaxe", Pickaxe],
  ["pine-tree", TreePine],
  ["pot-mix", CookingPot],
  ["recycle", Recycle],
  ["rice", Wheat],
  ["ring", Gem],
  ["road", Route],
  ["rocket", Rocket],
  ["ruler", Ruler],
  ["run-fast", Footprints],
  ["script-text", ScrollText],
  ["sheep", PawPrint],
  ["shield", Shield],
  ["shovel", Shovel],
  ["sign-direction", Signpost],
  ["ski", Mountain],
  ["snowboard", Mountain],
  ["snake", PawPrint],
  ["snowflake", Snowflake],
  ["spa", Sparkles],
  ["spear", Swords],
  ["sword", Swords],
  ["sprout", Sprout],
  ["stairs", TrendingUp],
  ["star", Star],
  ["store", Store],
  ["summit", Mountain],
  ["telescope", Telescope],
  ["temple", Landmark],
  ["tent", Tent],
  ["terrain", Mountain],
  ["thermometer", Thermometer],
  ["tractor", Wheat],
  ["train", TrainFront],
  ["translate", Languages],
  ["tree", Trees],
  ["trophy", Trophy],
  ["tunnel", Mountain],
  ["violin", Music],
  ["walk", Footprints],
  ["waterfall", Waves],
  ["water", Droplets],
  ["weather", CloudSun],
  ["sun", CloudSun],
  ["cloud", CloudSun],
  ["window", DoorOpen],
  ["yoga", Sparkles],
];

/** Resolves a taxonomy.json `mdi:` icon name to a lucide icon: exact category match first,
 * then the keyword table, then the given fallback (typically the parent category's icon). */
export function resolveTaxonomyIcon(mdiName: string, fallback: LucideIcon): LucideIcon {
  const exact = TAXONOMY_CATEGORY_ICONS[mdiName];
  if (exact) return exact;

  const name = mdiName.replace(/^mdi:/, "");
  for (const [keyword, icon] of KEYWORD_ICONS) {
    if (name.includes(keyword)) return icon;
  }
  return fallback;
}
