export const MOCK_SEARCH_PROFILES: NetworkProfileItem[] = [
  {
    id: "mock-profile-1",
    firstName: "Aarav",
    lastName: "Sharma",
    username: "aarav.clicks",
    bio: "Landscape photographer from Nainital",
    isFollowing: false,
  },
  {
    id: "mock-profile-2",
    firstName: "Priya",
    lastName: "Verma",
    username: "priya.travels",
    bio: "Chasing waterfalls across Uttarakhand",
    isFollowing: true,
  },
  {
    id: "mock-profile-3",
    firstName: "Rohan",
    lastName: "Mehta",
    username: "rohan.mehta",
    bio: "Street photography enthusiast",
    isFollowing: false,
  },
  {
    id: "mock-profile-4",
    firstName: "Ishita",
    lastName: "Rawat",
    username: "ishita.rawat",
    bio: "Mountains & monasteries",
    isFollowing: false,
  },
  {
    id: "mock-profile-5",
    firstName: "Vikram",
    lastName: "Singh",
    username: "vikram.singh",
    bio: "Wildlife & nature photographer",
    isFollowing: true,
  },
  {
    id: "mock-profile-6",
    firstName: "Ananya",
    lastName: "Bisht",
    username: "ananya.bisht",
    bio: "Documenting hidden Himalayan trails",
    isFollowing: false,
  },
  {
    id: "mock-profile-7",
    firstName: "Kabir",
    lastName: "Negi",
    username: "kabir.negi",
    bio: "Sunrise chaser",
    isFollowing: false,
  },
  {
    id: "mock-profile-8",
    firstName: "Meera",
    lastName: "Joshi",
    username: "meera.joshi",
    bio: "Food & culture of the hills",
    isFollowing: false,
  },
];

const HOUR_MS = 60 * 60 * 1000;
const now = Date.now();

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "mock-notif-1",
    type: "LIKE",
    message: "Priya Verma liked your post",
    actor: { name: "Priya Verma", username: "priya.travels" },
    isRead: false,
    createdAt: now - HOUR_MS * 1,
  },
  {
    id: "mock-notif-2",
    type: "FOLLOW",
    message: "Vikram Singh started following you",
    actor: { name: "Vikram Singh", username: "vikram.singh" },
    isRead: false,
    createdAt: now - HOUR_MS * 3,
  },
  {
    id: "mock-notif-3",
    type: "COMMENT",
    message: 'Rohan Mehta commented: "This view is unreal!"',
    actor: { name: "Rohan Mehta", username: "rohan.mehta" },
    isRead: true,
    createdAt: now - HOUR_MS * 8,
  },
  {
    id: "mock-notif-4",
    type: "AWARD",
    message: "You won Spotlight of the Week 🏆",
    isRead: true,
    createdAt: now - HOUR_MS * 26,
  },
  {
    id: "mock-notif-5",
    type: "LIKE",
    message: "Ananya Bisht and 12 others liked your post",
    actor: { name: "Ananya Bisht", username: "ananya.bisht" },
    isRead: true,
    createdAt: now - HOUR_MS * 50,
  },
  {
    id: "mock-notif-6",
    type: "FOLLOW",
    message: "Meera Joshi started following you",
    actor: { name: "Meera Joshi", username: "meera.joshi" },
    isRead: true,
    createdAt: now - HOUR_MS * 96,
  },
];
